/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yamidev.virtualclassroom.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.yamidev.virtualclassroom.model.BusinessAsset;
import com.yamidev.virtualclassroom.service.BusinessAssetLocalService;
import com.yamidev.virtualclassroom.service.persistence.BusinessAssetPersistence;
import com.yamidev.virtualclassroom.service.persistence.CoursePersistence;
import com.yamidev.virtualclassroom.service.persistence.CourseSessionPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Activos del negocio local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.yamidev.virtualclassroom.service.impl.BusinessAssetLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.yamidev.virtualclassroom.service.impl.BusinessAssetLocalServiceImpl
 * @generated
 */
public abstract class BusinessAssetLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, BusinessAssetLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BusinessAssetLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.yamidev.virtualclassroom.service.BusinessAssetLocalServiceUtil</code>.
	 */

	/**
	 * Adds the Activos del negocio to the database. Also notifies the appropriate model listeners.
	 *
	 * @param businessAsset the Activos del negocio
	 * @return the Activos del negocio that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BusinessAsset addBusinessAsset(BusinessAsset businessAsset) {
		businessAsset.setNew(true);

		return businessAssetPersistence.update(businessAsset);
	}

	/**
	 * Creates a new Activos del negocio with the primary key. Does not add the Activos del negocio to the database.
	 *
	 * @param businessAssetId the primary key for the new Activos del negocio
	 * @return the new Activos del negocio
	 */
	@Override
	@Transactional(enabled = false)
	public BusinessAsset createBusinessAsset(long businessAssetId) {
		return businessAssetPersistence.create(businessAssetId);
	}

	/**
	 * Deletes the Activos del negocio with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param businessAssetId the primary key of the Activos del negocio
	 * @return the Activos del negocio that was removed
	 * @throws PortalException if a Activos del negocio with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BusinessAsset deleteBusinessAsset(long businessAssetId)
		throws PortalException {

		return businessAssetPersistence.remove(businessAssetId);
	}

	/**
	 * Deletes the Activos del negocio from the database. Also notifies the appropriate model listeners.
	 *
	 * @param businessAsset the Activos del negocio
	 * @return the Activos del negocio that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BusinessAsset deleteBusinessAsset(BusinessAsset businessAsset) {
		return businessAssetPersistence.remove(businessAsset);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			BusinessAsset.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return businessAssetPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.yamidev.virtualclassroom.model.impl.BusinessAssetModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return businessAssetPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.yamidev.virtualclassroom.model.impl.BusinessAssetModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return businessAssetPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return businessAssetPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return businessAssetPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public BusinessAsset fetchBusinessAsset(long businessAssetId) {
		return businessAssetPersistence.fetchByPrimaryKey(businessAssetId);
	}

	/**
	 * Returns the Activos del negocio matching the UUID and group.
	 *
	 * @param uuid the Activos del negocio's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Activos del negocio, or <code>null</code> if a matching Activos del negocio could not be found
	 */
	@Override
	public BusinessAsset fetchBusinessAssetByUuidAndGroupId(
		String uuid, long groupId) {

		return businessAssetPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the Activos del negocio with the primary key.
	 *
	 * @param businessAssetId the primary key of the Activos del negocio
	 * @return the Activos del negocio
	 * @throws PortalException if a Activos del negocio with the primary key could not be found
	 */
	@Override
	public BusinessAsset getBusinessAsset(long businessAssetId)
		throws PortalException {

		return businessAssetPersistence.findByPrimaryKey(businessAssetId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(businessAssetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BusinessAsset.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("businessAssetId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			businessAssetLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(BusinessAsset.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"businessAssetId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(businessAssetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BusinessAsset.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("businessAssetId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<BusinessAsset>() {

				@Override
				public void performAction(BusinessAsset businessAsset)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, businessAsset);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(BusinessAsset.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return businessAssetPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return businessAssetLocalService.deleteBusinessAsset(
			(BusinessAsset)persistedModel);
	}

	public BasePersistence<BusinessAsset> getBasePersistence() {
		return businessAssetPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return businessAssetPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the Activos del negocios matching the UUID and company.
	 *
	 * @param uuid the UUID of the Activos del negocios
	 * @param companyId the primary key of the company
	 * @return the matching Activos del negocios, or an empty list if no matches were found
	 */
	@Override
	public List<BusinessAsset> getBusinessAssetsByUuidAndCompanyId(
		String uuid, long companyId) {

		return businessAssetPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of Activos del negocios matching the UUID and company.
	 *
	 * @param uuid the UUID of the Activos del negocios
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of Activos del negocios
	 * @param end the upper bound of the range of Activos del negocios (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching Activos del negocios, or an empty list if no matches were found
	 */
	@Override
	public List<BusinessAsset> getBusinessAssetsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<BusinessAsset> orderByComparator) {

		return businessAssetPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the Activos del negocio matching the UUID and group.
	 *
	 * @param uuid the Activos del negocio's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Activos del negocio
	 * @throws PortalException if a matching Activos del negocio could not be found
	 */
	@Override
	public BusinessAsset getBusinessAssetByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return businessAssetPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the Activos del negocios.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.yamidev.virtualclassroom.model.impl.BusinessAssetModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of Activos del negocios
	 * @param end the upper bound of the range of Activos del negocios (not inclusive)
	 * @return the range of Activos del negocios
	 */
	@Override
	public List<BusinessAsset> getBusinessAssets(int start, int end) {
		return businessAssetPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of Activos del negocios.
	 *
	 * @return the number of Activos del negocios
	 */
	@Override
	public int getBusinessAssetsCount() {
		return businessAssetPersistence.countAll();
	}

	/**
	 * Updates the Activos del negocio in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param businessAsset the Activos del negocio
	 * @return the Activos del negocio that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BusinessAsset updateBusinessAsset(BusinessAsset businessAsset) {
		return businessAssetPersistence.update(businessAsset);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			BusinessAssetLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		businessAssetLocalService = (BusinessAssetLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BusinessAssetLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BusinessAsset.class;
	}

	protected String getModelClassName() {
		return BusinessAsset.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = businessAssetPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected BusinessAssetLocalService businessAssetLocalService;

	@Reference
	protected BusinessAssetPersistence businessAssetPersistence;

	@Reference
	protected CoursePersistence coursePersistence;

	@Reference
	protected CourseSessionPersistence courseSessionPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}