/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pactia.co.active.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BusinessAsset service. Represents a row in the &quot;ps_BusinessAsset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.pactia.co.active.model.impl.BusinessAssetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.pactia.co.active.model.impl.BusinessAssetImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BusinessAsset
 * @generated
 */
@ProviderType
public interface BusinessAssetModel
	extends BaseModel<BusinessAsset>, GroupedModel, LocalizedModel,
			ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a business asset model instance should use the {@link BusinessAsset} interface instead.
	 */

	/**
	 * Returns the primary key of this business asset.
	 *
	 * @return the primary key of this business asset
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this business asset.
	 *
	 * @param primaryKey the primary key of this business asset
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this business asset.
	 *
	 * @return the uuid of this business asset
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this business asset.
	 *
	 * @param uuid the uuid of this business asset
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the business asset ID of this business asset.
	 *
	 * @return the business asset ID of this business asset
	 */
	public long getBusinessAssetId();

	/**
	 * Sets the business asset ID of this business asset.
	 *
	 * @param businessAssetId the business asset ID of this business asset
	 */
	public void setBusinessAssetId(long businessAssetId);

	/**
	 * Returns the group ID of this business asset.
	 *
	 * @return the group ID of this business asset
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this business asset.
	 *
	 * @param groupId the group ID of this business asset
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this business asset.
	 *
	 * @return the company ID of this business asset
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this business asset.
	 *
	 * @param companyId the company ID of this business asset
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this business asset.
	 *
	 * @return the user ID of this business asset
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this business asset.
	 *
	 * @param userId the user ID of this business asset
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this business asset.
	 *
	 * @return the user uuid of this business asset
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this business asset.
	 *
	 * @param userUuid the user uuid of this business asset
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this business asset.
	 *
	 * @return the user name of this business asset
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this business asset.
	 *
	 * @param userName the user name of this business asset
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this business asset.
	 *
	 * @return the create date of this business asset
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this business asset.
	 *
	 * @param createDate the create date of this business asset
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this business asset.
	 *
	 * @return the modified date of this business asset
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this business asset.
	 *
	 * @param modifiedDate the modified date of this business asset
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the asset code of this business asset.
	 *
	 * @return the asset code of this business asset
	 */
	@AutoEscape
	public String getAssetCode();

	/**
	 * Sets the asset code of this business asset.
	 *
	 * @param assetCode the asset code of this business asset
	 */
	public void setAssetCode(String assetCode);

	/**
	 * Returns the asset name of this business asset.
	 *
	 * @return the asset name of this business asset
	 */
	@AutoEscape
	public String getAssetName();

	/**
	 * Sets the asset name of this business asset.
	 *
	 * @param assetName the asset name of this business asset
	 */
	public void setAssetName(String assetName);

	/**
	 * Returns the asset address of this business asset.
	 *
	 * @return the asset address of this business asset
	 */
	@AutoEscape
	public String getAssetAddress();

	/**
	 * Sets the asset address of this business asset.
	 *
	 * @param assetAddress the asset address of this business asset
	 */
	public void setAssetAddress(String assetAddress);

	/**
	 * Returns the square meter value of this business asset.
	 *
	 * @return the square meter value of this business asset
	 */
	public double getSquareMeterValue();

	/**
	 * Sets the square meter value of this business asset.
	 *
	 * @param squareMeterValue the square meter value of this business asset
	 */
	public void setSquareMeterValue(double squareMeterValue);

	/**
	 * Returns the internal code of this business asset.
	 *
	 * @return the internal code of this business asset
	 */
	@AutoEscape
	public String getInternalCode();

	/**
	 * Sets the internal code of this business asset.
	 *
	 * @param internalCode the internal code of this business asset
	 */
	public void setInternalCode(String internalCode);

	/**
	 * Returns the marker map of this business asset.
	 *
	 * @return the marker map of this business asset
	 */
	public long getMarkerMap();

	/**
	 * Sets the marker map of this business asset.
	 *
	 * @param markerMap the marker map of this business asset
	 */
	public void setMarkerMap(long markerMap);

	/**
	 * Returns the description of this business asset.
	 *
	 * @return the description of this business asset
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this business asset in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this business asset
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this business asset in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this business asset. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this business asset in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this business asset
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this business asset in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this business asset
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this business asset.
	 *
	 * @return the locales and localized descriptions of this business asset
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this business asset.
	 *
	 * @param description the description of this business asset
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this business asset in the language.
	 *
	 * @param description the localized description of this business asset
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this business asset in the language, and sets the default locale.
	 *
	 * @param description the localized description of this business asset
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this business asset from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this business asset
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this business asset from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this business asset
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the logo of this business asset.
	 *
	 * @return the logo of this business asset
	 */
	public long getLogo();

	/**
	 * Sets the logo of this business asset.
	 *
	 * @param logo the logo of this business asset
	 */
	public void setLogo(long logo);

	/**
	 * Returns the latitude of this business asset.
	 *
	 * @return the latitude of this business asset
	 */
	public double getLatitude();

	/**
	 * Sets the latitude of this business asset.
	 *
	 * @param latitude the latitude of this business asset
	 */
	public void setLatitude(double latitude);

	/**
	 * Returns the longitude of this business asset.
	 *
	 * @return the longitude of this business asset
	 */
	public double getLongitude();

	/**
	 * Sets the longitude of this business asset.
	 *
	 * @param longitude the longitude of this business asset
	 */
	public void setLongitude(double longitude);

	/**
	 * Returns the city ID of this business asset.
	 *
	 * @return the city ID of this business asset
	 */
	@AutoEscape
	public String getCityId();

	/**
	 * Sets the city ID of this business asset.
	 *
	 * @param cityId the city ID of this business asset
	 */
	public void setCityId(String cityId);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}